allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@angular/common@21.2.15'
  - '@angular/compiler-cli@21.2.15'
  - '@angular/compiler@21.2.15'
  - '@angular/core@21.2.15'
  - '@angular/forms@21.2.15'
  - '@angular/localize@21.2.15'
  - '@angular/platform-browser@21.2.15'
  - '@angular/router@21.2.15'
  - '@myrmidon/cadmus-part-codicology-bindings@15.0.0'
  - '@myrmidon/cadmus-part-codicology-contents@15.0.0'
  - '@myrmidon/cadmus-part-codicology-decorations@15.0.0'
  - '@myrmidon/cadmus-part-codicology-edits@15.0.0'
  - '@myrmidon/cadmus-part-codicology-hands@15.0.0'
  - '@myrmidon/cadmus-part-codicology-layouts@15.0.0'
  - '@myrmidon/cadmus-part-codicology-material-dsc@15.0.0'
  - '@myrmidon/cadmus-part-codicology-pg@15.0.0'
  - '@myrmidon/cadmus-part-codicology-sheet-labels@15.0.0'
  - '@myrmidon/cadmus-part-codicology-shelfmarks@15.0.0'
  - '@myrmidon/cadmus-part-codicology-watermarks@15.0.0'
  - '@myrmidon/cadmus-part-general-pg@18.0.0'
  - '@myrmidon/cadmus-part-general-ui@18.0.1'
  - '@myrmidon/cadmus-part-ndp-notable-word-forms@1.0.0'
  - '@myrmidon/cadmus-part-ndp-pg@1.0.0'
  - '@myrmidon/cadmus-part-ndp-text-passages@1.0.0'
  - '@myrmidon/cadmus-part-ndpbooks-fig-plan@1.0.0'
  - '@myrmidon/cadmus-part-ndpbooks-fonts@1.0.0'
  - '@myrmidon/cadmus-part-ndpbooks-pg@1.0.0'
  - '@myrmidon/cadmus-part-philology-ui@19.0.1'
  - '@rollup/rollup-win32-arm64-msvc@4.62.0'
  - '@myrmidon/cadmus-codicology-ui@14.0.0'
